### ISSUE TITLE
Has anyone updated this for Kinetic ROS?

### ISSUE THREAD

**Issue by benwarrick** [florianshkurti/velodyne_simulator#1]
I'm working on updating this to work on Kinetic ROS, but I'm pretty new...

**Comment by lucbettaieb** [comment]
https://github.com/florianshkurti/velodyne_simulator/pull/4

**Comment by lucbettaieb** [comment]
@benwarrick

**Comment by lucbettaieb** [comment]
@florianshkurti This can be closed

**Comment by lucbettaieb** [comment]
@benwarrick @florianshkurti
